apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  repositories: |
    - name: ecr
      type: ecr
      url: $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

---
apiVersion: argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: my-app
  namespace: argocd
spec:
  application: my-app
  repoURL: https://your-git-repo-url.git
  target:
    revision: HEAD
    path: path/to/your/helm/chart
  interval: 5m
  updateStrategy:
    helm:
      valuesFile: values.yaml
  image:
    repository: $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/my-app
    tagPattern: "*"

